version: "3.9"
name: bsw-test


services:
  line-provider:
    image: bsw-test-line-provider
    build:
      context: ../inline-provider

    volumes:
      - ../inline-provider:/app

    ports:
      - "8080:8080"
