version: "3.9"
name: bsw-test


x-betmaker_base: &betmaker_base
  image: bsw-test-bet-maker
  build:
    context: ../bet-maker

  volumes:
    - ../bet-maker:/app

  environment:
    DB_CONNECTION_STRING: 'postgresql+psycopg2://postgres:dev@db:5432/postgres'
    REDIS_HOST: 'redis'

  links:
    - db
    - line-provider
    - redis

services:
  line-provider:
    image: bsw-test-line-provider
    build:
      context: ../inline-provider

    volumes:
      - ../inline-provider:/app

    environment:
      REDIS_HOST: redis

    links:
      - redis

    ports:
      - "8080:8080"

  bet-maker:
    <<: *betmaker_base

    ports:
      - "8000:8000"

  bet-maker-consumer:
    <<: *betmaker_base
    command: [ "consumer" ]

  db:
    image: postgres:16

    volumes:
      - db:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: dev

  redis:
    image: redis


volumes:
  db: