version: "3.9"
name: bsw-test


services:
  line-provider:
    image: bsw-test-line-provider
    build:
      context: ../inline-provider

    volumes:
      - ../inline-provider:/app

    ports:
      - "8080:8080"

  bet-maker:
    image: bsw-test-bet-maker
    build:
      context: ../bet-maker

    volumes:
      - ../bet-maker:/app

    ports:
      - "8000:8000"
